#!/usr/bin/env bash

# bash 'safe' mode
set -euo pipefail
IFS=$'\n\t'

export WERCKER_BITBUCKET_BUILDSTATUS_PASSED_MESSAGE="$WERCKER_APPLICATION_OWNER_NAME/$WERCKER_APPLICATION_NAME: build of $WERCKER_GIT_BRANCH by $WERCKER_STARTED_BY passed."
export WERCKER_BITBUCKET_BUILDSTATUS_FAILED_MESSAGE="$WERCKER_APPLICATION_OWNER_NAME/$WERCKER_APPLICATION_NAME: build of $WERCKER_GIT_BRANCH by $WERCKER_STARTED_BY failed."

export WERCKER_BITBUCKET_BUILDSTATUS_URL="https://api.bitbucket.org/2.0/repositories/$WERCKER_BITBUCKET_BUILDSTATUS_OWNER/$WERCKER_APPLICATION_NAME/commit/$WERCKER_GIT_COMMIT/statuses/build"

if [ "$WERCKER_RESULT" = "passed" ]; then
  export WERCKER_BITBUCKET_BUILDSTATUS_STATE="SUCCESSFUL"
  export WERCKER_BITBUCKET_BUILDSTATUS_DESCRIPTION="$WERCKER_BITBUCKET_BUILDSTATUS_PASSED_MESSAGE"
else
  export WERCKER_BITBUCKET_BUILDSTATUS_STATE="FAILED"
  export WERCKER_BITBUCKET_BUILDSTATUS_DESCRIPTION="$WERCKER_BITBUCKET_BUILDSTATUS_FAILED_MESSAGE"
fi

json="{\"state\": \"$WERCKER_BITBUCKET_BUILDSTATUS_STATE\", \"key\": \"$WERCKER_BUILD_ID\", \"name\": \"$WERCKER_APPLICATION_NAME\", \"url\": \"$WERCKER_BUILD_URL\", \"description\": \"$WERCKER_BITBUCKET_BUILDSTATUS_DESCRIPTION\"}"

RESULT=$(curl -u "$WERCKER_BITBUCKET_BUILDSTATUS_USERNAME:$WERCKER_BITBUCKET_BUILDSTATUS_PASSWORD" -X POST -d "$json" -H "Content-Type: application/json" "$WERCKER_BITBUCKET_BUILDSTATUS_URL" -w "%{http_code}")

if [ "$RESULT" = "500" ]; then
  fatal "Server error on Bitbucket"
fi

if [ "$RESULT" = "401" ]; then
  fatal "Forbidden: Invalid authentication credentials supplied"
fi

if [ "$RESULT" = "404" ]; then
  fatal "Owner, application or changeset not found"
fi
